# Generated by Django 5.1.5 on 2025-01-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('class_10_year', models.IntegerField()),
                ('class_12_year', models.IntegerField()),
                ('class_10_marks', models.FloatField()),
                ('class_12_marks', models.FloatField()),
                ('experience_years', models.FloatField()),
                ('last_job_title', models.CharField(max_length=255)),
                ('companies', models.TextField()),
                ('cities', models.TextField()),
                ('college', models.CharField(max_length=255)),
                ('extracurricular_activities', models.TextField()),
                ('certificates', models.TextField()),
            ],
        ),
    ]
